[build]
  command = "npm run build:frontend"
  publish = "./frontend/_static"

[functions]
  directory = "backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200